export interface ServiceCenter {
  id: string
  name: string
  category: string
  subCategory: string
  phone: string
  altPhone?: string
  website: string
  locationUrl?: string
  operatingHours: string
  description: string
  services: string[]
  logo: string
}

export const categories = [
  { id: "electronics", name: "전자제품", icon: "Tv" },
  { id: "telecom", name: "통신사", icon: "Smartphone" },
  { id: "automotive", name: "자동차", icon: "Car" },
  { id: "finance", name: "금융·보험", icon: "Landmark" },
  { id: "shopping", name: "쇼핑·배송", icon: "ShoppingBag" },
  { id: "food", name: "식품·음료", icon: "Coffee" },
  { id: "travel", name: "여행·항공", icon: "Plane" },
  { id: "life", name: "생활서비스", icon: "Home" },
  { id: "government", name: "공공기관", icon: "Building2" },
  { id: "healthcare", name: "의료·건강", icon: "Heart" },
  { id: "entertainment", name: "엔터테인먼트", icon: "Gamepad2" },
  { id: "computer", name: "컴퓨터·IT", icon: "Laptop" },
]

export const serviceCenters: ServiceCenter[] = [
  // ==================== 전자제품 ====================
  {
    id: "samsung-electronics",
    name: "삼성전자 서비스센터",
    category: "electronics",
    subCategory: "가전·모바일",
    phone: "1588-3366",
    website: "https://www.samsungsvc.co.kr",
    locationUrl: "https://www.samsungsvc.co.kr/location",
    operatingHours: "평일 09:00~18:00 / 토요일 09:00~13:00",
    description: "삼성전자 서비스센터는 갤럭시 스마트폰, 태블릿, TV, 냉장고, 세탁기, 에어컨 등 삼성전자의 모든 제품에 대한 수리 및 AS 서비스를 제공합니다. 전국 180여 개의 서비스센터를 통해 전문 엔지니어가 빠르고 정확한 서비스를 제공하며, 출장 수리 서비스와 택배 수리 서비스도 이용 가능합니다. 삼성 멤버스 앱을 통해 예약 및 진행 상황 확인이 가능합니다.",
    services: ["스마트폰 수리", "가전제품 수리", "출장 서비스", "택배 수리", "제품 상담"],
    logo: "/logos/samsung.svg"
  },
  {
    id: "lg-electronics",
    name: "LG전자 서비스센터",
    category: "electronics",
    subCategory: "가전·모바일",
    phone: "1544-7777",
    website: "https://www.lgservice.co.kr",
    locationUrl: "https://www.lgservice.co.kr/center",
    operatingHours: "평일 09:00~18:00 / 토요일 09:00~13:00",
    description: "LG전자 서비스센터는 LG 스마트폰, OLED TV, 냉장고, 세탁기, 에어컨, 스타일러 등 LG전자 전 제품의 수리 및 점검 서비스를 제공합니다. 전국 서비스 네트워크를 통해 방문 수리, 출장 수리, 원격 진단 서비스를 이용할 수 있으며, LG ThinQ 앱을 통한 스마트 진단 기능도 제공됩니다.",
    services: ["가전제품 수리", "출장 서비스", "원격 진단", "제품 상담", "부품 구매"],
    logo: "/logos/lg.svg"
  },
  {
    id: "apple-korea",
    name: "Apple 고객지원",
    category: "electronics",
    subCategory: "모바일·컴퓨터",
    phone: "080-333-4000",
    altPhone: "1599-2772",
    website: "https://support.apple.com/ko-kr",
    locationUrl: "https://locate.apple.com/kr/ko/",
    operatingHours: "평일 09:00~18:00",
    description: "Apple 고객지원센터는 iPhone, iPad, Mac, Apple Watch, AirPods 등 모든 Apple 제품에 대한 기술 지원 및 수리 서비스를 제공합니다. Apple Store 및 Apple 공인 서비스 제공업체를 통해 전문적인 수리 서비스를 받을 수 있으며, AppleCare+ 가입 고객은 우선 지원을 받을 수 있습니다. 수리 서비스 예약은 별도 번호로 가능합니다.",
    services: ["iPhone 수리", "Mac 수리", "기술 지원", "AppleCare+", "제품 상담"],
    logo: "/logos/apple.svg"
  },
  {
    id: "sony-korea",
    name: "소니코리아 고객센터",
    category: "electronics",
    subCategory: "영상·음향기기",
    phone: "1588-0911",
    website: "https://www.sony.co.kr/support",
    locationUrl: "https://www.sony.co.kr/support/service-center",
    operatingHours: "평일 09:00~18:00",
    description: "소니코리아 고객센터는 플레이스테이션, 미러리스 카메라, 헤드폰, 사운드바, 브라비아 TV 등 소니 제품 전반에 대한 기술 지원 및 AS 서비스를 제공합니다. 제품 사용법 안내, 수리 접수, 정품 등록, 펌웨어 업데이트 안내 등 다양한 서비스를 이용할 수 있습니다.",
    services: ["플레이스테이션 수리", "카메라 수리", "음향기기 수리", "제품 상담", "펌웨어 안내"],
    logo: "/logos/sony.svg"
  },
  {
    id: "dyson-korea",
    name: "다이슨 고객센터",
    category: "electronics",
    subCategory: "소형가전",
    phone: "1588-4253",
    altPhone: "080-300-4253",
    website: "https://www.dyson.co.kr/support",
    locationUrl: "https://www.dyson.co.kr/support/service-centers",
    operatingHours: "평일 09:00~18:00 / 토요일 09:00~13:00",
    description: "다이슨 고객센터는 무선청소기(V시리즈, Gen5detect), 헤어드라이어(슈퍼소닉), 공기청정기(퓨어쿨), 에어랩 등 다이슨 제품에 대한 전문적인 수리 및 상담 서비스를 제공합니다. 다이슨 데모 스토어 및 서비스센터를 통해 직접 방문 수리도 가능합니다.",
    services: ["무선청소기 수리", "헤어드라이어 수리", "공기청정기 점검", "에어랩 수리", "부품 구매"],
    logo: "/logos/dyson.svg"
  },
  {
    id: "philips-korea",
    name: "필립스 고객센터",
    category: "electronics",
    subCategory: "소형가전",
    phone: "080-600-6600",
    website: "https://www.philips.co.kr",
    operatingHours: "평일 09:00~18:00",
    description: "필립스 고객센터는 전기면도기, 구강관리기기(소닉케어), 에어프라이어, 헤어드라이어 등 필립스 제품에 대한 수리 및 상담 서비스를 제공합니다. 소모품 구매 안내 및 제품 사용법 상담도 가능합니다.",
    services: ["면도기 수리", "소닉케어 수리", "에어프라이어 수리", "소모품 구매", "제품 상담"],
    logo: "/logos/philips.svg"
  },
  {
    id: "coway",
    name: "코웨이 고객센터",
    category: "electronics",
    subCategory: "렌탈·정수기",
    phone: "1588-5200",
    website: "https://www.coway.com",
    locationUrl: "https://www.coway.com/cs/center",
    operatingHours: "평일 09:00~18:00 / 토요일 09:00~13:00",
    description: "코웨이 고객센터는 정수기, 공기청정기, 비데, 매트리스 등 코웨이 렌탈 제품에 대한 설치, 이전, 점검, AS 서비스를 제공합니다. 코디(코웨이 전문 관리사) 방문 일정 조정 및 필터 교체 서비스도 신청할 수 있습니다.",
    services: ["정수기 AS", "공기청정기 점검", "비데 수리", "코디 방문 예약", "필터 교체"],
    logo: "/logos/coway.svg"
  },
  {
    id: "sk-magic",
    name: "SK매직 고객센터",
    category: "electronics",
    subCategory: "렌탈·정수기",
    phone: "1600-1661",
    altPhone: "1670-4550",
    website: "https://www.skmagic.com",
    operatingHours: "평일 09:00~18:00",
    description: "SK매직 고객센터는 정수기, 공기청정기, 식기세척기, 인덕션 등 SK매직 렌탈 및 판매 제품에 대한 설치, AS, 이전 서비스를 제공합니다. 매직케어 방문 관리 서비스 예약 및 렌탈 계약 관련 상담도 가능합니다.",
    services: ["정수기 AS", "식기세척기 수리", "렌탈 상담", "매직케어 예약", "제품 설치"],
    logo: "/logos/sk-magic.svg"
  },

  // ==================== 통신사 ====================
  {
    id: "skt",
    name: "SK텔레콤 고객센터",
    category: "telecom",
    subCategory: "이동통신",
    phone: "114",
    altPhone: "1599-0011",
    website: "https://www.tworld.co.kr",
    locationUrl: "https://www.tworld.co.kr/poc/store",
    operatingHours: "24시간 ARS / 상담원 09:00~18:00",
    description: "SK텔레콤 고객센터는 이동통신 서비스, 요금제 변경, 로밍 서비스, T멤버십 혜택 등에 대한 종합 상담을 제공합니다. T월드 앱과 웹사이트를 통해 요금 조회, 요금제 변경, 부가서비스 신청 등을 편리하게 이용할 수 있습니다. 휴대폰에서 114로 무료 연결됩니다.",
    services: ["요금 조회", "요금제 변경", "로밍 서비스", "T멤버십", "분실 신고"],
    logo: "/logos/skt.svg"
  },
  {
    id: "kt",
    name: "KT 고객센터",
    category: "telecom",
    subCategory: "이동통신·인터넷",
    phone: "100",
    altPhone: "1588-0010",
    website: "https://www.kt.com",
    locationUrl: "https://www.kt.com/store",
    operatingHours: "24시간 ARS / 상담원 09:00~18:00",
    description: "KT 고객센터는 이동통신, 인터넷, IPTV(올레tv), 유선전화 등 KT의 모든 통신 서비스에 대한 상담을 제공합니다. 마이KT 앱을 통해 실시간 데이터 사용량 확인, 요금 조회, 각종 신청 업무를 처리할 수 있으며, KT 플라자 방문을 통해 대면 상담도 가능합니다.",
    services: ["요금 조회", "인터넷 장애 신고", "올레tv 상담", "로밍 서비스", "기기 변경"],
    logo: "/logos/kt.svg"
  },
  {
    id: "lguplus",
    name: "LG유플러스 고객센터",
    category: "telecom",
    subCategory: "이동통신·인터넷",
    phone: "114",
    altPhone: "1544-0010",
    website: "https://www.lguplus.com",
    locationUrl: "https://www.lguplus.com/shop/find-store",
    operatingHours: "24시간 ARS / 상담원 09:00~18:00",
    description: "LG유플러스 고객센터는 5G/LTE 이동통신, 초고속 인터넷, U+tv, IoT 서비스 등에 대한 종합 상담을 제공합니다. 당신의 U+ 앱을 통해 요금 조회, 데이터 선물, 멤버십 혜택 이용이 가능하며, 전국 LG유플러스 매장에서 대면 상담도 가능합니다.",
    services: ["요금 조회", "인터넷 상담", "U+tv 상담", "IoT 서비스", "멤버십 혜택"],
    logo: "/logos/lguplus.svg"
  },
  {
    id: "tplus",
    name: "티플러스(T Plus) 고객센터",
    category: "telecom",
    subCategory: "알뜰폰",
    phone: "1877-9114",
    altPhone: "1811-1141",
    website: "https://www.tplus.co.kr",
    operatingHours: "평일 09:00~18:00",
    description: "티플러스 고객센터는 SKT, KT, LG U+ 망을 사용하는 알뜰폰 서비스에 대한 요금제 상담, 가입/해지, 데이터 충전 등의 서비스를 제공합니다. 사용 중인 통신망에 따라 고객센터 번호가 다를 수 있습니다.",
    services: ["요금제 상담", "가입/해지", "데이터 충전", "요금 조회", "유심 배송"],
    logo: "/logos/tplus.svg"
  },
  {
    id: "hello-mobile",
    name: "헬로모바일 고객센터",
    category: "telecom",
    subCategory: "알뜰폰",
    phone: "1855-1144",
    website: "https://www.cjhellomobile.com",
    operatingHours: "평일 09:00~18:00",
    description: "헬로모바일 고객센터는 CJ헬로에서 운영하는 알뜰폰 서비스로, 다양한 요금제와 데이터 서비스에 대한 상담을 제공합니다. SKT, KT, LG U+ 망 중 선택하여 이용할 수 있습니다.",
    services: ["요금제 상담", "가입 상담", "데이터 충전", "명의변경", "해지 상담"],
    logo: "/logos/hello-mobile.svg"
  },
  {
    id: "freet",
    name: "프리티 고객센터",
    category: "telecom",
    subCategory: "알뜰폰",
    phone: "1661-2207",
    altPhone: "1577-4551",
    website: "https://www.freet.co.kr",
    operatingHours: "평일 09:00~18:00",
    description: "프리티 고객센터는 저렴한 요금제를 제공하는 알뜰폰 서비스로, 통신망별로 다양한 요금제를 선택할 수 있습니다. 온라인 전용 요금제부터 오프라인 가입까지 다양한 서비스를 제공합니다.",
    services: ["요금제 안내", "가입 상담", "요금 조회", "유심 발송", "해지 상담"],
    logo: "/logos/freet.svg"
  },

  // ==================== 자동차 ====================
  {
    id: "hyundai-motor",
    name: "현대자동차 고객센터",
    category: "automotive",
    subCategory: "국산차",
    phone: "080-600-6000",
    website: "https://www.hyundai.com/kr",
    locationUrl: "https://www.hyundai.com/kr/ko/customer-service/service-network",
    operatingHours: "평일 08:30~18:00 / 긴급출동 24시간",
    description: "현대자동차 고객센터는 차량 구매 상담, 정비 예약, 긴급출동 서비스, 보증 수리 등 현대자동차 소유 고객을 위한 종합 서비스를 제공합니다. 블루핸즈 서비스센터 네트워크를 통해 전국 어디서나 전문적인 정비 서비스를 받을 수 있으며, 현대 블루멤버스 앱을 통해 차량 관리 및 각종 혜택을 이용할 수 있습니다.",
    services: ["차량 정비", "긴급출동", "보증 수리", "부품 구매", "차량 상담"],
    logo: "/logos/hyundai.svg"
  },
  {
    id: "kia-motor",
    name: "기아자동차 고객센터",
    category: "automotive",
    subCategory: "국산차",
    phone: "080-200-2000",
    website: "https://www.kia.com/kr",
    locationUrl: "https://www.kia.com/kr/customer-service/service-network",
    operatingHours: "평일 08:30~19:00 / 주말 09:00~17:00",
    description: "기아자동차 고객센터는 기아 차량 소유 고객을 위한 정비, 수리, 긴급출동 등의 서비스를 제공합니다. 오토큐 서비스센터를 통해 전문 정비 서비스를 받을 수 있으며, Kia Members 앱을 통해 편리하게 정비 예약 및 차량 관리가 가능합니다.",
    services: ["차량 정비", "긴급출동", "보증 수리", "순정부품", "차량 상담"],
    logo: "/logos/kia.svg"
  },
  {
    id: "genesis",
    name: "제네시스 고객센터",
    category: "automotive",
    subCategory: "프리미엄",
    phone: "080-700-6000",
    website: "https://www.genesis.com/kr",
    locationUrl: "https://www.genesis.com/kr/ko/support.html",
    operatingHours: "평일 08:30~18:00 / 긴급출동 24시간",
    description: "제네시스 고객센터는 프리미엄 서비스를 제공하는 제네시스 전용 고객센터입니다. 전담 컨시어지 서비스, 픽업&딜리버리 서비스, 제네시스 버틀러 등 차별화된 프리미엄 서비스를 경험할 수 있습니다.",
    services: ["제네시스 버틀러", "픽업딜리버리", "긴급출동", "정비 예약", "컨시어지"],
    logo: "/logos/genesis.svg"
  },
  {
    id: "bmw-korea",
    name: "BMW코리아 고객센터",
    category: "automotive",
    subCategory: "수입차",
    phone: "080-700-8000",
    website: "https://www.bmw.co.kr",
    locationUrl: "https://www.bmw.co.kr/ko/topics/offers-and-services/dealer-search.html",
    operatingHours: "평일 09:00~18:00",
    description: "BMW코리아 고객센터는 BMW 차량 소유 고객을 위한 프리미엄 서비스를 제공합니다. 공식 서비스센터를 통한 전문 정비, BSI(BMW Service Inclusive) 프로그램, 24시간 긴급출동 서비스 등을 이용할 수 있습니다.",
    services: ["차량 정비", "24시간 긴급출동", "BSI 프로그램", "순정부품", "차량 상담"],
    logo: "/logos/bmw.svg"
  },
  {
    id: "mercedes-benz-korea",
    name: "메르세데스-벤츠 고객센터",
    category: "automotive",
    subCategory: "수입차",
    phone: "1577-2320",
    altPhone: "080-001-1886",
    website: "https://www.mercedes-benz.co.kr",
    locationUrl: "https://www.mercedes-benz.co.kr/passengercars/being-an-owner/service.html",
    operatingHours: "평일 09:00~18:00",
    description: "메르세데스-벤츠 고객센터는 벤츠 차량 소유 고객을 위한 최고 수준의 서비스를 제공합니다. 공식 서비스센터에서의 전문 정비, 24시간 모빌로 긴급출동 서비스, 정품 부품 제공 등 프리미엄 서비스를 경험할 수 있습니다.",
    services: ["차량 정비", "모빌로 긴급출동", "정품 부품", "연장 보증", "차량 상담"],
    logo: "/logos/mercedes.svg"
  },
  {
    id: "toyota-korea",
    name: "토요타코리아 고객센터",
    category: "automotive",
    subCategory: "수입차",
    phone: "080-525-8255",
    website: "https://www.toyota.co.kr",
    locationUrl: "https://www.toyota.co.kr/service/center",
    operatingHours: "평일 09:00~18:00",
    description: "토요타코리아 고객센터는 토요타 차량의 정비, 수리, 부품 구매 등에 대한 서비스를 제공합니다. 전국 공식 서비스센터 네트워크를 통해 전문적인 정비 서비스를 받을 수 있습니다.",
    services: ["차량 정비", "부품 구매", "보증 수리", "사고 수리", "차량 상담"],
    logo: "/logos/toyota.svg"
  },
  {
    id: "lexus-korea",
    name: "렉서스코리아 고객센터",
    category: "automotive",
    subCategory: "수입차",
    phone: "080-4500-4500",
    website: "https://www.lexus.co.kr",
    locationUrl: "https://www.lexus.co.kr/service/center",
    operatingHours: "24시간 서비스 예약 가능",
    description: "렉서스코리아 고객센터는 렉서스 차량 소유 고객을 위한 프리미엄 서비스를 제공합니다. 24시간 서비스 예약이 가능하며, 전담 서비스 어드바이저를 통한 맞춤형 서비스를 받을 수 있습니다.",
    services: ["차량 정비", "24시간 예약", "긴급출동", "프리미엄 서비스", "부품 구매"],
    logo: "/logos/lexus.svg"
  },
  {
    id: "honda-korea",
    name: "혼다코리아 고객센터",
    category: "automotive",
    subCategory: "수입차",
    phone: "080-360-0505",
    website: "https://www.honda.co.kr",
    operatingHours: "평일 09:00~18:00",
    description: "혼다코리아 고객센터는 혼다 자동차 및 오토바이에 대한 정비, 수리, 부품 구매 서비스를 제공합니다. 공식 딜러 네트워크를 통해 전문적인 서비스를 받을 수 있습니다.",
    services: ["차량 정비", "오토바이 수리", "부품 구매", "보증 수리", "차량 상담"],
    logo: "/logos/honda.svg"
  },
  {
    id: "kg-mobility",
    name: "KG모빌리티 고객센터",
    category: "automotive",
    subCategory: "국산차",
    phone: "080-500-5582",
    altPhone: "02-818-5581",
    website: "https://www.kg-mobility.com",
    locationUrl: "https://www.kg-mobility.com/service",
    operatingHours: "평일 09:00~18:00 / 긴급출동 24시간",
    description: "KG모빌리티(구 쌍용자동차) 고객센터는 토레스, 티볼리, 렉스턴 등 KG모빌리티 차량에 대한 정비, 수리, 긴급출동 서비스를 제공합니다. 전국 서비스센터 네트워크를 통해 전문적인 정비 서비스를 받을 수 있습니다.",
    services: ["차량 정비", "긴급출동", "보증 수리", "부품 구매", "사고 수리"],
    logo: "/logos/kg-mobility.svg"
  },

  // ==================== 금융·보험 ====================
  {
    id: "kb-bank",
    name: "KB국민은행 고객센터",
    category: "finance",
    subCategory: "은행",
    phone: "1588-9999",
    altPhone: "1599-9999",
    website: "https://www.kbstar.com",
    locationUrl: "https://obank.kbstar.com/quics?page=C016528",
    operatingHours: "24시간 ARS / 상담원 09:00~18:00",
    description: "KB국민은행 고객센터는 예금, 대출, 외환, 펀드, 보험 등 종합 금융 상담을 제공합니다. KB스타뱅킹 앱을 통해 계좌 조회, 이체, 대출 신청 등 다양한 금융 서비스를 이용할 수 있으며, 전국 지점을 통한 대면 상담도 가능합니다.",
    services: ["계좌 조회", "이체 서비스", "대출 상담", "외환 서비스", "분실 신고"],
    logo: "/logos/kb.svg"
  },
  {
    id: "shinhan-bank",
    name: "신한은행 고객센터",
    category: "finance",
    subCategory: "은행",
    phone: "1577-8000",
    altPhone: "1599-8000",
    website: "https://www.shinhan.com",
    locationUrl: "https://www.shinhan.com/hpe/index.jsp#011000000000",
    operatingHours: "24시간 ARS / 상담원 09:00~18:00",
    description: "신한은행 고객센터는 예적금, 대출, 투자, 보험 등 종합 금융 서비스 상담을 제공합니다. 쏠(SOL) 앱을 통해 편리한 모바일 뱅킹 서비스를 이용할 수 있으며, 화상 상담 서비스도 제공됩니다.",
    services: ["계좌 조회", "이체 서비스", "대출 상담", "투자 상담", "보험 상담"],
    logo: "/logos/shinhan.svg"
  },
  {
    id: "hana-bank",
    name: "하나은행 고객센터",
    category: "finance",
    subCategory: "은행",
    phone: "1588-1111",
    altPhone: "1599-1111",
    website: "https://www.kebhana.com",
    locationUrl: "https://www.kebhana.com/cont/mall/mall08/index.jsp",
    operatingHours: "24시간 ARS / 상담원 09:00~18:00",
    description: "하나은행 고객센터는 예금, 대출, 외환, 투자 등 종합 금융 상담을 제공합니다. 하나원큐 앱을 통해 간편하게 금융 서비스를 이용할 수 있으며, 외환 전문 은행으로서 해외송금 서비스가 특화되어 있습니다.",
    services: ["계좌 조회", "이체 서비스", "대출 상담", "외환 서비스", "해외송금"],
    logo: "/logos/hana.svg"
  },
  {
    id: "woori-bank",
    name: "우리은행 고객센터",
    category: "finance",
    subCategory: "은행",
    phone: "1588-5000",
    altPhone: "1599-5000",
    website: "https://www.wooribank.com",
    operatingHours: "24시간 ARS / 상담원 09:00~18:00",
    description: "우리은행 고객센터는 예적금, 대출, 외환, 자산관리 등 종합 금융 서비스를 제공합니다. 우리WON뱅킹 앱을 통해 편리하게 금융 서비스를 이용할 수 있습니다.",
    services: ["계좌 조회", "이체 서비스", "대출 상담", "자산관리", "분실 신고"],
    logo: "/logos/woori.svg"
  },
  {
    id: "nh-bank",
    name: "NH농협은행 고객센터",
    category: "finance",
    subCategory: "은행",
    phone: "1661-3000",
    altPhone: "1522-3000",
    website: "https://www.nonghyup.com",
    operatingHours: "24시간 ARS / 상담원 09:00~18:00",
    description: "NH농협은행 고객센터는 예적금, 대출, 보험, 투자 등 종합 금융 서비스를 제공합니다. NH올원뱅크 앱을 통해 간편하게 금융 서비스를 이용할 수 있으며, 전국 농협 지점 네트워크를 통한 대면 상담도 가능합니다.",
    services: ["계좌 조회", "이체 서비스", "대출 상담", "보험 상담", "농업금융"],
    logo: "/logos/nh.svg"
  },
  {
    id: "ibk-bank",
    name: "IBK기업은행 고객센터",
    category: "finance",
    subCategory: "은행",
    phone: "1566-2566",
    altPhone: "1588-2588",
    website: "https://www.ibk.co.kr",
    operatingHours: "24시간 ARS / 상담원 09:00~18:00",
    description: "IBK기업은행 고객센터는 기업금융 전문 은행으로 중소기업 대출, 예금, 외환 등의 서비스를 제공합니다. 개인 고객을 위한 종합 금융 서비스도 함께 제공됩니다.",
    services: ["기업대출", "계좌 조회", "이체 서비스", "외환 서비스", "기업금융"],
    logo: "/logos/ibk.svg"
  },
  {
    id: "kakao-bank",
    name: "카카오뱅크 고객센터",
    category: "finance",
    subCategory: "인터넷은행",
    phone: "1599-3333",
    website: "https://www.kakaobank.com",
    operatingHours: "24시간 ARS / 상담원 09:00~22:00",
    description: "카카오뱅크 고객센터는 모바일 전용 인터넷 은행으로, 예금, 대출, 해외송금 등의 서비스를 제공합니다. 카카오뱅크 앱을 통해 간편하게 모든 금융 서비스를 이용할 수 있습니다.",
    services: ["계좌 조회", "이체 서비스", "대출 상담", "해외송금", "체크카드"],
    logo: "/logos/kakao-bank.svg"
  },
  {
    id: "toss-bank",
    name: "토스뱅크 고객센터",
    category: "finance",
    subCategory: "인터넷은행",
    phone: "1661-7654",
    website: "https://www.tossbank.com",
    operatingHours: "24시간 ARS / 상담원 09:00~18:00",
    description: "토스뱅크 고객센터는 토스 앱 기반 인터넷 은행으로, 예금, 대출, 체크카드 등의 서비스를 제공합니다. 토스 앱에서 원스톱으로 모든 금융 서비스를 이용할 수 있습니다.",
    services: ["계좌 조회", "이체 서비스", "대출 상담", "체크카드", "자산관리"],
    logo: "/logos/toss.svg"
  },
  {
    id: "samsung-card",
    name: "삼성카드 고객센터",
    category: "finance",
    subCategory: "카드",
    phone: "1588-8700",
    website: "https://www.samsungcard.com",
    operatingHours: "24시간 ARS / 상담원 09:00~18:00",
    description: "삼성카드 고객센터는 카드 발급, 결제 조회, 포인트 확인, 분실 신고 등 삼성카드 관련 모든 서비스를 제공합니다. 삼성카드 앱을 통해 실시간 결제 알림, 혜택 확인, 각종 금융 서비스를 편리하게 이용할 수 있습니다.",
    services: ["카드 발급", "결제 조회", "분실 신고", "포인트 조회", "해외 사용"],
    logo: "/logos/samsung-card.svg"
  },
  {
    id: "kb-card",
    name: "KB국민카드 고객센터",
    category: "finance",
    subCategory: "카드",
    phone: "1588-1688",
    website: "https://card.kbcard.com",
    operatingHours: "24시간 ARS / 상담원 09:00~18:00",
    description: "KB국민카드 고객센터는 카드 발급, 이용내역 조회, 포인트리 적립/사용, 분실 신고 등의 서비스를 제공합니다. KB Pay 앱을 통해 간편결제 및 카드 관리가 가능합니다.",
    services: ["카드 발급", "이용내역 조회", "포인트리", "분실 신고", "결제일 변경"],
    logo: "/logos/kb-card.svg"
  },
  {
    id: "shinhan-card",
    name: "신한카드 고객센터",
    category: "finance",
    subCategory: "카드",
    phone: "1544-7000",
    website: "https://www.shinhancard.com",
    operatingHours: "24시간 ARS / 상담원 09:00~18:00",
    description: "신한카드 고객센터는 카드 발급, 결제 조회, 마이신한포인트, 분실 신고 등의 서비스를 제공합니다. 신한플레이 앱을 통해 카드 관리 및 간편결제가 가능합니다.",
    services: ["카드 발급", "결제 조회", "마이신한포인트", "분실 신고", "해외 결제"],
    logo: "/logos/shinhan-card.svg"
  },
  {
    id: "hyundai-card",
    name: "현대카드 고객센터",
    category: "finance",
    subCategory: "카드",
    phone: "1577-6000",
    altPhone: "1588-6789",
    website: "https://www.hyundaicard.com",
    operatingHours: "24시간 ARS / 상담원 09:00~18:00",
    description: "현대카드 고객센터는 카드 발급, M포인트, 결제 조회, 분실 신고 등의 서비스를 제공합니다. 현대카드 앱을 통해 PLCC 카드별 혜택 확인 및 관리가 가능합니다.",
    services: ["카드 발급", "M포인트", "결제 조회", "분실 신고", "PLCC 혜택"],
    logo: "/logos/hyundai-card.svg"
  },
  {
    id: "woori-card",
    name: "우리카드 고객센터",
    category: "finance",
    subCategory: "카드",
    phone: "1588-9955",
    website: "https://pc.wooricard.com",
    operatingHours: "24시간 ARS / 상담원 09:00~18:00",
    description: "우리카드 고객센터는 카드 발급, 이용내역 조회, 포인트, 분실 신고 등의 서비스를 제공합니다. 우리WON카드 앱을 통해 편리하게 카드 관리가 가능합니다.",
    services: ["카드 발급", "이용내역 조회", "포인트 조회", "분실 신고", "결제일 변경"],
    logo: "/logos/woori-card.svg"
  },
  {
    id: "samsung-life",
    name: "삼성생명 고객센터",
    category: "finance",
    subCategory: "보험",
    phone: "1588-3114",
    website: "https://www.samsunglife.com",
    operatingHours: "평일 09:00~18:00",
    description: "삼성생명 고객센터는 생명보험 가입, 보험금 청구, 계약 조회, 대출 상담 등의 서비스를 제공합니다. 삼성생명 앱을 통해 보험 관리 및 보험금 청구가 가능합니다.",
    services: ["보험 상담", "보험금 청구", "계약 조회", "보험 대출", "증명서 발급"],
    logo: "/logos/samsung-life.svg"
  },
  {
    id: "hanwha-life",
    name: "한화생명 고객센터",
    category: "finance",
    subCategory: "보험",
    phone: "1588-6363",
    website: "https://www.hanwhalife.com",
    operatingHours: "평일 09:00~18:00",
    description: "한화생명 고객센터는 생명보험 가입, 보험금 청구, 계약 변경, 대출 상담 등의 서비스를 제공합니다. 한화생명 앱을 통해 보험 관리가 가능합니다.",
    services: ["보험 상담", "보험금 청구", "계약 변경", "보험 대출", "연금 상담"],
    logo: "/logos/hanwha-life.svg"
  },
  {
    id: "kyobo-life",
    name: "교보생명 고객센터",
    category: "finance",
    subCategory: "보험",
    phone: "1588-1001",
    website: "https://www.kyobo.com",
    operatingHours: "평일 09:00~18:00",
    description: "교보생명 고객센터는 생명보험 가입, 보험금 청구, 계약 조회, 교보다솜케어 서비스 등을 제공합니다. 교보생명 앱을 통해 편리하게 보험 관리가 가능합니다.",
    services: ["보험 상담", "보험금 청구", "계약 조회", "다솜케어", "증명서 발급"],
    logo: "/logos/kyobo.svg"
  },
  {
    id: "samsung-fire",
    name: "삼성화재 고객센터",
    category: "finance",
    subCategory: "보험",
    phone: "1588-5114",
    website: "https://www.samsungfire.com",
    operatingHours: "24시간 긴급출동 / 상담원 09:00~18:00",
    description: "삼성화재 고객센터는 자동차보험, 화재보험, 여행자보험 등 손해보험 상담 및 보험금 청구 서비스를 제공합니다. 긴급출동 서비스는 24시간 이용 가능합니다.",
    services: ["자동차보험", "긴급출동", "보험금 청구", "화재보험", "여행자보험"],
    logo: "/logos/samsung-fire.svg"
  },
  {
    id: "db-insurance",
    name: "DB손해보험 고객센터",
    category: "finance",
    subCategory: "보험",
    phone: "1588-0100",
    website: "https://www.idbins.com",
    operatingHours: "24시간 긴급출동 / 상담원 09:00~18:00",
    description: "DB손해보험 고객센터는 자동차보험, 운전자보험, 여행자보험 등 손해보험 상담 및 보험금 청구 서비스를 제공합니다. 24시간 긴급출동 서비스를 운영합니다.",
    services: ["자동차보험", "긴급출동", "보험금 청구", "운전자보험", "여행자보험"],
    logo: "/logos/db-insurance.svg"
  },

  // ==================== 쇼핑·배송 ====================
  {
    id: "coupang",
    name: "쿠팡 고객센터",
    category: "shopping",
    subCategory: "온라인쇼핑",
    phone: "1577-7011",
    website: "https://www.coupang.com",
    operatingHours: "365일 09:00~22:00",
    description: "쿠팡 고객센터는 주문 조회, 배송 문의, 반품/교환, 로켓배송 관련 모든 문의에 대응합니다. 쿠팡 앱과 웹사이트를 통해 실시간 배송 추적, 간편 반품 신청 등을 이용할 수 있으며, 로켓와우 회원은 무료 반품 서비스를 이용할 수 있습니다.",
    services: ["주문 조회", "배송 추적", "반품/교환", "로켓배송", "결제 문의"],
    logo: "/logos/coupang.svg"
  },
  {
    id: "naver-shopping",
    name: "네이버쇼핑 고객센터",
    category: "shopping",
    subCategory: "온라인쇼핑",
    phone: "1588-3820",
    website: "https://help.naver.com",
    operatingHours: "평일 09:00~18:00",
    description: "네이버 고객센터는 네이버 쇼핑, 네이버페이, 네이버 멤버십 등 네이버 서비스 전반에 대한 상담을 제공합니다. 네이버톡톡을 통한 실시간 채팅 상담도 가능합니다.",
    services: ["네이버쇼핑", "네이버페이", "멤버십", "포인트 조회", "스마트스토어"],
    logo: "/logos/naver.svg"
  },
  {
    id: "11st",
    name: "11번가 고객센터",
    category: "shopping",
    subCategory: "온라인쇼핑",
    phone: "1599-0110",
    website: "https://www.11st.co.kr",
    operatingHours: "평일 09:00~18:00",
    description: "11번가 고객센터는 주문, 결제, 배송, 반품/교환 등 11번가 이용과 관련된 모든 문의에 대응합니다. SK페이 포인트 적립 및 다양한 할인 혜택 문의도 가능합니다.",
    services: ["주문 조회", "배송 추적", "반품/교환", "SK페이", "포인트 적립"],
    logo: "/logos/11st.svg"
  },
  {
    id: "gmarket",
    name: "G마켓 고객센터",
    category: "shopping",
    subCategory: "온라인쇼핑",
    phone: "1566-5701",
    website: "https://www.gmarket.co.kr",
    operatingHours: "평일 09:00~18:00",
    description: "G마켓 고객센터는 주문, 결제, 배송 문의 등 G마켓 이용 관련 상담을 제공합니다. 스마일페이, 스마일카드 관련 문의도 처리 가능합니다.",
    services: ["주문 조회", "배송 문의", "반품/교환", "스마일페이", "판매자 문의"],
    logo: "/logos/gmarket.svg"
  },
  {
    id: "auction",
    name: "옥션 고객센터",
    category: "shopping",
    subCategory: "온라인쇼핑",
    phone: "1588-0184",
    website: "https://www.auction.co.kr",
    operatingHours: "평일 09:00~18:00",
    description: "옥션 고객센터는 주문, 결제, 배송, 경매 관련 문의에 대응합니다. G마켓과 통합된 이베이코리아 서비스로 스마일페이 이용이 가능합니다.",
    services: ["주문 조회", "배송 문의", "반품/교환", "경매 문의", "스마일페이"],
    logo: "/logos/auction.svg"
  },
  {
    id: "ssg",
    name: "SSG닷컴 고객센터",
    category: "shopping",
    subCategory: "온라인쇼핑",
    phone: "1577-3419",
    website: "https://www.ssg.com",
    operatingHours: "365일 09:00~21:00",
    description: "SSG닷컴 고객센터는 신세계, 이마트 온라인몰 통합 고객센터로 주문, 배송, 새벽배송, 반품/교환 관련 문의에 대응합니다. SSG머니 및 신세계포인트 관련 상담도 가능합니다.",
    services: ["주문 조회", "새벽배송", "반품/교환", "SSG머니", "신세계포인트"],
    logo: "/logos/ssg.svg"
  },
  {
    id: "lotte-on",
    name: "롯데온 고객센터",
    category: "shopping",
    subCategory: "온라인쇼핑",
    phone: "1899-1010",
    website: "https://www.lotteon.com",
    operatingHours: "평일 09:00~18:00",
    description: "롯데온 고객센터는 롯데그룹 통합 온라인쇼핑몰로 주문, 배송, 반품/교환 관련 상담을 제공합니다. L.POINT 적립 및 사용 관련 문의도 가능합니다.",
    services: ["주문 조회", "배송 추적", "반품/교환", "L.POINT", "멤버십"],
    logo: "/logos/lotte-on.svg"
  },
  {
    id: "kurly",
    name: "마켓컬리 고객센터",
    category: "shopping",
    subCategory: "온라인쇼핑",
    phone: "1644-1107",
    website: "https://www.kurly.com",
    operatingHours: "365일 07:00~23:00",
    description: "마켓컬리 고객센터는 신선식품 새벽배송 전문몰로 주문, 배송, 상품 문의에 대응합니다. 컬리 퍼플박스를 통한 친환경 포장 서비스도 제공합니다.",
    services: ["주문 조회", "새벽배송", "상품 문의", "반품/교환", "컬리패스"],
    logo: "/logos/kurly.svg"
  },
  {
    id: "musinsa",
    name: "무신사 고객센터",
    category: "shopping",
    subCategory: "패션",
    phone: "1544-7199",
    website: "https://www.musinsa.com",
    operatingHours: "평일 09:00~18:00",
    description: "무신사 고객센터는 패션 전문 온라인몰로 주문, 배송, 교환/반품, 무신사 스탠다드 관련 문의에 대응합니다. 무신사 포인트 및 회원 등급 관련 상담도 가능합니다.",
    services: ["주문 조회", "배송 추적", "반품/교환", "무신사포인트", "브랜드 문의"],
    logo: "/logos/musinsa.svg"
  },
  {
    id: "ably",
    name: "에이블리 고객센터",
    category: "shopping",
    subCategory: "패션",
    phone: "1833-8021",
    website: "https://www.a-bly.com",
    operatingHours: "평일 10:00~18:00",
    description: "에이블리 고객센터는 여성 패션 전문 앱으로 주문, 배송, 반품/교환 관련 문의에 대응합니다. 에이블리 포인트 및 쿠폰 관련 상담도 가능합니다.",
    services: ["주문 조회", "배송 추적", "반품/교환", "포인트", "셀러 문의"],
    logo: "/logos/ably.svg"
  },
  {
    id: "cj-logistics",
    name: "CJ대한통운 고객센터",
    category: "shopping",
    subCategory: "택배",
    phone: "1588-1255",
    website: "https://www.cjlogistics.com",
    locationUrl: "https://www.cjlogistics.com/ko/tool/parcel/tracking",
    operatingHours: "평일 09:00~18:00 / 토요일 09:00~13:00",
    description: "CJ대한통운 고객센터는 택배 접수, 배송 조회, 분실/파손 신고 등 택배 서비스 전반에 대한 상담을 제공합니다. CJ대한통운 앱을 통해 실시간 배송 추적 및 부재시 배송 위치 지정 서비스를 이용할 수 있습니다.",
    services: ["택배 접수", "배송 조회", "분실 신고", "반품 택배", "예약 배송"],
    logo: "/logos/cj.svg"
  },
  {
    id: "lotte-logistics",
    name: "롯데택배 고객센터",
    category: "shopping",
    subCategory: "택배",
    phone: "1588-2121",
    website: "https://www.lotteglogis.com",
    operatingHours: "평일 09:00~18:00",
    description: "롯데택배 고객센터는 택배 접수, 배송 조회, 분실/파손 신고 등의 서비스를 제공합니다. 롯데글로벌로지스 앱을 통해 배송 조회가 가능합니다.",
    services: ["택배 접수", "배송 조회", "분실 신고", "반품 택배", "방문 수거"],
    logo: "/logos/lotte-logistics.svg"
  },
  {
    id: "hanjin",
    name: "한진택배 고객센터",
    category: "shopping",
    subCategory: "택배",
    phone: "1588-0011",
    website: "https://www.hanjin.co.kr",
    operatingHours: "평일 09:00~18:00",
    description: "한진택배 고객센터는 택배 접수, 배송 조회, 분실/파손 신고 등의 서비스를 제공합니다. 한진택배 앱 및 카카오톡 채널을 통해 편리하게 배송 조회가 가능합니다.",
    services: ["택배 접수", "배송 조회", "분실 신고", "반품 택배", "국제특송"],
    logo: "/logos/hanjin.svg"
  },

  // ==================== 식품·음료 ====================
  {
    id: "baemin",
    name: "배달의민족 고객센터",
    category: "food",
    subCategory: "배달",
    phone: "1577-0000",
    website: "https://www.baemin.com",
    operatingHours: "평일 09:00~18:00",
    description: "배달의민족 고객센터는 주문 문의, 결제 문의, 배달 지연, 환불 등 배달 서비스 전반에 대한 상담을 제공합니다. 배민앱 내 1:1 채팅 상담을 통해 빠른 문제 해결이 가능합니다.",
    services: ["주문 문의", "배달 추적", "환불 요청", "리뷰 관리", "가게 문의"],
    logo: "/logos/baemin.svg"
  },
  {
    id: "yogiyo",
    name: "요기요 고객센터",
    category: "food",
    subCategory: "배달",
    phone: "1661-5270",
    website: "https://www.yogiyo.co.kr",
    operatingHours: "24시간 운영",
    description: "요기요 고객센터는 주문, 배달, 결제, 환불 등 요기요 이용 관련 모든 문의에 24시간 대응합니다. 요기패스 구독 및 포인트 관련 상담도 가능합니다.",
    services: ["주문 문의", "배달 추적", "환불 요청", "요기패스", "포인트"],
    logo: "/logos/yogiyo.svg"
  },
  {
    id: "coupang-eats",
    name: "쿠팡이츠 고객센터",
    category: "food",
    subCategory: "배달",
    phone: "1670-9827",
    website: "https://www.coupangeats.com",
    operatingHours: "06:00~03:00",
    description: "쿠팡이츠 고객센터는 음식 배달 주문, 결제, 환불 등에 대한 상담을 제공합니다. 쿠팡이츠 앱을 통해 실시간 배달 추적이 가능합니다.",
    services: ["주문 문의", "배달 추적", "환불 요청", "쿠폰 문의", "가게 문의"],
    logo: "/logos/coupang-eats.svg"
  },
  {
    id: "starbucks-korea",
    name: "스타벅스 고객센터",
    category: "food",
    subCategory: "카페",
    phone: "1522-3232",
    website: "https://www.starbucks.co.kr",
    locationUrl: "https://www.starbucks.co.kr/store/store_map.do",
    operatingHours: "평일 09:00~18:00",
    description: "스타벅스 고객센터는 매장 이용, 스타벅스 리워드, e-Gift Card, 사이렌 오더 등에 대한 상담을 제공합니다. 스타벅스 앱을 통해 사이렌 오더, 별 적립, 프리퀀시 이벤트 참여가 가능합니다.",
    services: ["매장 안내", "리워드 문의", "e-Gift 카드", "사이렌 오더", "프리퀀시"],
    logo: "/logos/starbucks.svg"
  },
  {
    id: "twosome",
    name: "투썸플레이스 고객센터",
    category: "food",
    subCategory: "카페",
    phone: "1577-4410",
    website: "https://www.twosome.co.kr",
    locationUrl: "https://www.twosome.co.kr/store",
    operatingHours: "평일 09:00~18:00",
    description: "투썸플레이스 고객센터는 매장 이용, 멤버십, 케이크 예약, 모바일 주문 등에 대한 상담을 제공합니다. 투썸하트 앱을 통해 포인트 적립 및 모바일 주문이 가능합니다.",
    services: ["매장 안내", "케이크 예약", "모바일 주문", "멤버십", "포인트"],
    logo: "/logos/twosome.svg"
  },
  {
    id: "baekdabang",
    name: "빽다방 고객센터",
    category: "food",
    subCategory: "카페",
    phone: "1544-2360",
    website: "https://paikdabang.com",
    locationUrl: "https://paikdabang.com/store",
    operatingHours: "평일 09:00~18:00",
    description: "빽다방 고객센터는 매장 이용, 메뉴 문의, 배달 서비스 등에 대한 상담을 제공합니다. 합리적인 가격의 커피와 음료로 인기 있는 프랜차이즈입니다.",
    services: ["매장 안내", "메뉴 문의", "배달 문의", "창업 문의", "제휴 문의"],
    logo: "/logos/baekdabang.svg"
  },
  {
    id: "compose",
    name: "컴포즈커피 고객센터",
    category: "food",
    subCategory: "카페",
    phone: "1899-5685",
    website: "https://www.composecoffee.com",
    operatingHours: "평일 09:00~18:00",
    description: "컴포즈커피 고객센터는 매장 이용, 메뉴, 포인트 등에 대한 상담을 제공합니다. 가성비 좋은 커피로 빠르게 성장하고 있는 프랜차이즈입니다.",
    services: ["매장 안내", "메뉴 문의", "포인트 적립", "창업 문의", "제휴 문의"],
    logo: "/logos/compose.svg"
  },
  {
    id: "mcdonalds-korea",
    name: "맥도날드 고객센터",
    category: "food",
    subCategory: "패스트푸드",
    phone: "1600-5252",
    altPhone: "080-208-1588",
    website: "https://www.mcdonalds.co.kr",
    locationUrl: "https://www.mcdonalds.co.kr/kor/store/list.do",
    operatingHours: "09:00~21:00",
    description: "맥도날드 고객센터는 매장 이용, 맥딜리버리, 해피밀, 메뉴 관련 문의에 대응합니다. 맥도날드 앱을 통해 모바일 주문, 딜리버리 서비스, 쿠폰 사용이 가능합니다.",
    services: ["매장 안내", "맥딜리버리", "모바일 주문", "해피밀", "쿠폰"],
    logo: "/logos/mcdonalds.svg"
  },
  {
    id: "kfc-korea",
    name: "KFC 고객센터",
    category: "food",
    subCategory: "패스트푸드",
    phone: "1577-8484",
    website: "https://www.kfckorea.com",
    locationUrl: "https://www.kfckorea.com/store/find.html",
    operatingHours: "평일 09:00~18:00",
    description: "KFC 고객센터는 매장 이용, 배달 서비스, 메뉴 관련 문의에 대응합니다. KFC 앱을 통해 모바일 주문 및 딜리버리 서비스를 이용할 수 있습니다.",
    services: ["매장 안내", "배달 서비스", "모바일 주문", "메뉴 문의", "쿠폰"],
    logo: "/logos/kfc.svg"
  },
  {
    id: "lotteria",
    name: "롯데리아 고객센터",
    category: "food",
    subCategory: "패스트푸드",
    phone: "080-550-0005",
    altPhone: "02-709-1114",
    website: "https://www.lotteria.com",
    locationUrl: "https://www.lotteria.com/Store",
    operatingHours: "평일 09:00~18:00",
    description: "롯데리아 고객센터는 매장 이용, 배달 서비스, 롯데잇츠 앱 관련 문의에 대응합니다. L.POINT 적립 및 다양한 할인 혜택을 이용할 수 있습니다.",
    services: ["매장 안내", "배달 서비스", "롯데잇츠", "L.POINT", "쿠폰"],
    logo: "/logos/lotteria.svg"
  },
  {
    id: "domino",
    name: "도미노피자 고객센터",
    category: "food",
    subCategory: "피자",
    phone: "1577-3082",
    altPhone: "080-860-3082",
    website: "https://www.dominos.co.kr",
    locationUrl: "https://www.dominos.co.kr/store/find",
    operatingHours: "10:30~24:00",
    description: "도미노피자 고객센터는 피자 주문, 배달, 매장 픽업 등에 대한 상담을 제공합니다. 도미노 앱을 통해 간편하게 주문하고 실시간 배달 추적이 가능합니다.",
    services: ["피자 주문", "배달 서비스", "매장 픽업", "쿠폰", "멤버십"],
    logo: "/logos/domino.svg"
  },
  {
    id: "bbq",
    name: "BBQ치킨 고객센터",
    category: "food",
    subCategory: "치킨",
    phone: "1588-9282",
    website: "https://www.bbq.co.kr",
    locationUrl: "https://www.bbq.co.kr/store",
    operatingHours: "10:00~23:00",
    description: "BBQ치킨 고객센터는 치킨 주문, 배달, 메뉴 문의 등에 대한 상담을 제공합니다. BBQ 앱을 통해 간편하게 주문하고 포인트 적립이 가능합니다.",
    services: ["치킨 주문", "배달 서비스", "매장 픽업", "포인트", "쿠폰"],
    logo: "/logos/bbq.svg"
  },
  {
    id: "kyochon",
    name: "교촌치킨 고객센터",
    category: "food",
    subCategory: "치킨",
    phone: "080-320-3000",
    website: "https://www.kyochonfnb.com",
    locationUrl: "https://www.kyochonfnb.com/store/find.do",
    operatingHours: "12:00~24:00",
    description: "교촌치킨 고객센터는 치킨 주문, 배달, 메뉴 문의 등에 대한 상담을 제공합니다. 교촌 앱을 통해 간편하게 주문하고 멤버십 혜택을 이용할 수 있습니다.",
    services: ["치킨 주문", "배달 서비스", "매장 픽업", "멤버십", "쿠폰"],
    logo: "/logos/kyochon.svg"
  },

  // ==================== 여행·항공 ====================
  {
    id: "korean-air",
    name: "대한항공 고객센터",
    category: "travel",
    subCategory: "항공사",
    phone: "1588-2001",
    altPhone: "02-2656-2001",
    website: "https://www.koreanair.com",
    operatingHours: "한국어 07:00~22:00 / 영어 24시간",
    description: "대한항공 고객센터는 항공권 예약, 스케줄 조회, 마일리지 적립/사용, 수하물 문의 등 항공 서비스 전반에 대한 상담을 제공합니다. 대한항공 앱을 통해 모바일 체크인, 탑승권 발급, 좌석 선택 등이 가능합니다.",
    services: ["항공권 예약", "스케줄 조회", "마일리지", "수하물", "라운지"],
    logo: "/logos/koreanair.svg"
  },
  {
    id: "asiana",
    name: "아시아나항공 고객센터",
    category: "travel",
    subCategory: "항공사",
    phone: "1588-8000",
    altPhone: "02-2669-8000",
    website: "https://flyasiana.com",
    operatingHours: "24시간 운영",
    description: "아시아나항공 고객센터는 항공권 예약, 변경, 취소, 아시아나클럽 마일리지 등에 대한 상담을 제공합니다. 아시아나 앱을 통해 간편하게 예약 및 체크인이 가능합니다.",
    services: ["항공권 예약", "예약 변경", "마일리지", "수하물", "라운지"],
    logo: "/logos/asiana.svg"
  },
  {
    id: "jeju-air",
    name: "제주항공 고객센터",
    category: "travel",
    subCategory: "항공사",
    phone: "1599-1500",
    website: "https://www.jejuair.net",
    operatingHours: "06:00~23:00",
    description: "제주항공 고객센터는 저비용항공사로 항공권 예약, 변경, 취소, 추가 서비스 등에 대한 상담을 제공합니다. JJ멤버스 포인트 적립 및 사용이 가능합니다.",
    services: ["항공권 예약", "예약 변경", "JJ멤버스", "수하물", "좌석 선택"],
    logo: "/logos/jejuair.svg"
  },
  {
    id: "jinair",
    name: "진에어 고객센터",
    category: "travel",
    subCategory: "항공사",
    phone: "1600-6200",
    altPhone: "02-6099-1200",
    website: "https://www.jinair.com",
    operatingHours: "09:00~18:00",
    description: "진에어 고객센터는 대한항공 자회사 저비용항공사로 항공권 예약, 변경, 취소 등에 대한 상담을 제공합니다. 나비포인트 적립 및 사용이 가능합니다.",
    services: ["항공권 예약", "예약 변경", "나비포인트", "수하물", "좌석 선택"],
    logo: "/logos/jinair.svg"
  },
  {
    id: "twayair",
    name: "티웨이항공 고객센터",
    category: "travel",
    subCategory: "항공사",
    phone: "1688-8686",
    website: "https://www.twayair.com",
    operatingHours: "06:00~22:00",
    description: "티웨이항공 고객센터는 저비용항공사로 항공권 예약, 변경, 부가 서비스 등에 대한 상담을 제공합니다. 티웨이 멤버십 포인트 적립이 가능합니다.",
    services: ["항공권 예약", "예약 변경", "멤버십", "수하물", "좌석 선택"],
    logo: "/logos/twayair.svg"
  },
  {
    id: "airbusan",
    name: "에어부산 고객센터",
    category: "travel",
    subCategory: "항공사",
    phone: "1666-3060",
    altPhone: "051-410-0787",
    website: "https://www.airbusan.com",
    operatingHours: "06:00~22:00",
    description: "에어부산 고객센터는 아시아나항공 자회사 저비용항공사로 항공권 예약, 변경, 취소 등에 대한 상담을 제공합니다. 아시아나클럽 마일리지 적립이 가능합니다.",
    services: ["항공권 예약", "예약 변경", "마일리지", "수하물", "좌석 선택"],
    logo: "/logos/airbusan.svg"
  },
  {
    id: "airseoul",
    name: "에어서울 고객센터",
    category: "travel",
    subCategory: "항공사",
    phone: "1800-8100",
    website: "https://flyairseoul.com",
    operatingHours: "09:00~18:00",
    description: "에어서울 고객센터는 아시아나항공 자회사 저비용항공사로 항공권 예약, 변경, 취소 등에 대한 상담을 제공합니다.",
    services: ["항공권 예약", "예약 변경", "수하물", "좌석 선택", "기내식"],
    logo: "/logos/airseoul.svg"
  },
  {
    id: "eastar",
    name: "이스타항공 고객센터",
    category: "travel",
    subCategory: "항공사",
    phone: "1544-0080",
    website: "https://www.eastarjet.com",
    operatingHours: "09:00~18:00",
    description: "이스타항공 고객센터는 저비용항공사로 항공권 예약, 변경, 취소, 부가 서비스 등에 대한 상담을 제공합니다.",
    services: ["항공권 예약", "예약 변경", "수하물", "좌석 선택", "기내식"],
    logo: "/logos/eastar.svg"
  },
  {
    id: "hanatour",
    name: "하나투어 고객센터",
    category: "travel",
    subCategory: "여행사",
    phone: "1577-1233",
    altPhone: "1899-1833",
    website: "https://www.hanatour.com",
    operatingHours: "평일 09:00~18:00",
    description: "하나투어 고객센터는 패키지여행, 항공권, 호텔, 자유여행 상품 등에 대한 상담을 제공합니다. 여행 출발 전후 각종 문의에 대응합니다.",
    services: ["패키지여행", "항공권", "호텔 예약", "자유여행", "비자 상담"],
    logo: "/logos/hanatour.svg"
  },
  {
    id: "yanolja",
    name: "야놀자 고객센터",
    category: "travel",
    subCategory: "숙박예약",
    phone: "1644-1346",
    website: "https://www.yanolja.com",
    operatingHours: "09:00~03:00",
    description: "야놀자 고객센터는 숙박 예약, 결제 문의, 취소/환불, 리뷰 관련 모든 문의에 대응합니다. 야놀자 앱을 통해 실시간 예약 확인 및 특가 상품 이용이 가능합니다.",
    services: ["숙박 예약", "결제 문의", "취소/환불", "포인트", "파트너 문의"],
    logo: "/logos/yanolja.svg"
  },
  {
    id: "yeogi",
    name: "여기어때 고객센터",
    category: "travel",
    subCategory: "숙박예약",
    phone: "1670-6250",
    website: "https://www.goodchoice.kr",
    operatingHours: "09:00~03:00",
    description: "여기어때 고객센터는 숙박 예약, 결제, 취소/환불 관련 모든 문의에 대응합니다. 여기어때 앱을 통해 다양한 숙소를 실시간 예약할 수 있습니다.",
    services: ["숙박 예약", "결제 문의", "취소/환불", "포인트", "쿠폰"],
    logo: "/logos/yeogi.svg"
  },
  {
    id: "agoda",
    name: "아고다 고객센터",
    category: "travel",
    subCategory: "숙박예약",
    phone: "070-4784-4366",
    website: "https://www.agoda.com",
    operatingHours: "평일 09:00~21:00 / 주말 09:00~17:30",
    description: "아고다 고객센터는 글로벌 호텔 예약 플랫폼으로 전 세계 숙소 예약, 결제, 취소/환불 관련 상담을 제공합니다. 아고다 앱을 통해 특가 예약이 가능합니다.",
    services: ["호텔 예약", "결제 문의", "취소/환불", "애그미캐시", "리뷰"],
    logo: "/logos/agoda.svg"
  },

  // ==================== 생활서비스 ====================
  {
    id: "kepco",
    name: "한국전력공사 고객센터",
    category: "life",
    subCategory: "에너지",
    phone: "123",
    website: "https://online.kepco.co.kr",
    operatingHours: "24시간 긴급신고 / 상담원 09:00~18:00",
    description: "한국전력공사 고객센터는 전기요금 조회, 납부, 정전 신고, 전기 안전 점검 등의 서비스를 제공합니다. 한전ON 앱을 통해 편리하게 요금 조회 및 납부가 가능합니다.",
    services: ["요금 조회", "요금 납부", "정전 신고", "안전 점검", "계약 변경"],
    logo: "/logos/kepco.svg"
  },
  {
    id: "seoul-gas",
    name: "서울도시가스 고객센터",
    category: "life",
    subCategory: "에너지",
    phone: "1588-5788",
    altPhone: "1544-0119",
    website: "https://www.seoulgas.co.kr",
    operatingHours: "24시간 긴급신고 / 상담원 09:00~18:00",
    description: "서울도시가스 고객센터는 가스 사용량 조회, 요금 납부, 가스 누출 신고, 계량기 점검 등의 서비스를 제공합니다. 가스 누출 등 안전 관련 긴급 신고는 24시간 대응합니다.",
    services: ["요금 조회", "요금 납부", "가스 누출 신고", "계량기 점검", "개폐 신청"],
    logo: "/logos/seoulgas.svg"
  },
  {
    id: "yesco",
    name: "예스코 고객센터",
    category: "life",
    subCategory: "에너지",
    phone: "1544-3131",
    website: "https://www.yesco.co.kr",
    operatingHours: "24시간 긴급신고 / 상담원 09:00~18:00",
    description: "예스코 고객센터는 서울 일부 지역 도시가스 공급사로 가스 요금 조회, 납부, 안전 점검 등의 서비스를 제공합니다.",
    services: ["요금 조회", "요금 납부", "가스 누출 신고", "안전 점검", "개폐 신청"],
    logo: "/logos/yesco.svg"
  },
  {
    id: "kowon",
    name: "코원에너지 고객센터",
    category: "life",
    subCategory: "에너지",
    phone: "1599-3366",
    website: "https://www.kowon.co.kr",
    operatingHours: "24시간 긴급신고 / 상담원 09:00~18:00",
    description: "코원에너지서비스 고객센터는 서울 일부 지역 도시가스 공급사로 가스 요금 조회, 납부, 안전 점검 등의 서비스를 제공합니다.",
    services: ["요금 조회", "요금 납부", "가스 누출 신고", "안전 점검", "개폐 신청"],
    logo: "/logos/kowon.svg"
  },
  {
    id: "seoul-water",
    name: "서울시 상수도 다산콜센터",
    category: "life",
    subCategory: "상수도",
    phone: "120",
    website: "https://arisu.seoul.go.kr",
    operatingHours: "24시간 운영",
    description: "서울시 상수도 다산콜센터는 수도요금 조회, 누수 신고, 수질 문의, 개폐 신청 등 상수도 서비스 전반에 대한 상담을 제공합니다.",
    services: ["요금 조회", "누수 신고", "수질 문의", "개폐 신청", "명의 변경"],
    logo: "/logos/seoul.svg"
  },
  {
    id: "hanssem",
    name: "한샘 고객센터",
    category: "life",
    subCategory: "가구·인테리어",
    phone: "1588-0000",
    website: "https://www.hanssem.com",
    locationUrl: "https://www.hanssem.com/store",
    operatingHours: "평일 09:00~18:00",
    description: "한샘 고객센터는 주방가구, 인테리어, 리모델링, 가구 등에 대한 상담 및 AS 서비스를 제공합니다. 전국 전시장을 통해 직접 상담받을 수 있습니다.",
    services: ["가구 상담", "리모델링", "AS 신청", "배송 문의", "설치 서비스"],
    logo: "/logos/hanssem.svg"
  },
  {
    id: "emart",
    name: "이마트 고객센터",
    category: "life",
    subCategory: "대형마트",
    phone: "02-380-5678",
    website: "https://store.emart.com",
    locationUrl: "https://store.emart.com/branch/list.do",
    operatingHours: "평일 10:00~17:00",
    description: "이마트 고객센터는 매장 이용, 상품 문의, 신세계포인트, 배송 서비스 등에 대한 상담을 제공합니다. 이마트앱을 통해 전단행사 및 쿠폰 확인이 가능합니다.",
    services: ["매장 안내", "상품 문의", "신세계포인트", "배송 서비스", "쿠폰"],
    logo: "/logos/emart.svg"
  },
  {
    id: "homeplus",
    name: "홈플러스 고객센터",
    category: "life",
    subCategory: "대형마트",
    phone: "02-3459-8000",
    website: "https://corporate.homeplus.co.kr",
    locationUrl: "https://corporate.homeplus.co.kr/store/store.aspx",
    operatingHours: "평일 09:00~18:00",
    description: "홈플러스 고객센터는 매장 이용, 온라인 주문, 마이홈플러스 멤버십 등에 대한 상담을 제공합니다. 홈플러스 앱을 통해 간편하게 쇼핑할 수 있습니다.",
    services: ["매장 안내", "온라인 주문", "마이홈플러스", "배송 서비스", "쿠폰"],
    logo: "/logos/homeplus.svg"
  },
  {
    id: "lottemart",
    name: "롯데마트 고객센터",
    category: "life",
    subCategory: "대형마트",
    phone: "1899-7000",
    website: "https://www.lottemart.com",
    locationUrl: "https://www.lottemart.com/branch/main.do",
    operatingHours: "평일 09:00~18:00",
    description: "롯데마트 고객센터는 매장 이용, 온라인 주문, L.POINT 적립 등에 대한 상담을 제공합니다. 롯데마트GO 앱을 통해 스마트 쇼핑이 가능합니다.",
    services: ["매장 안내", "온라인 주문", "L.POINT", "배송 서비스", "쿠폰"],
    logo: "/logos/lottemart.svg"
  },
  {
    id: "costco",
    name: "코스트코 고객센터",
    category: "life",
    subCategory: "대형마트",
    phone: "1899-9900",
    website: "https://www.costco.co.kr",
    locationUrl: "https://www.costco.co.kr/store-finder",
    operatingHours: "평일 09:00~18:00",
    description: "코스트코 고객센터는 회원 전용 창고형 할인매장으로 회원 가입, 매장 이용, 반품/교환 등에 대한 상담을 제공합니다.",
    services: ["회원 가입", "매장 안내", "반품/교환", "온라인 주문", "배송 서비스"],
    logo: "/logos/costco.svg"
  },
  {
    id: "gs25",
    name: "GS25 고객센터",
    category: "life",
    subCategory: "편의점",
    phone: "080-999-5425",
    altPhone: "1644-5425",
    website: "https://gs25.gsretail.com",
    operatingHours: "24시간 운영",
    description: "GS25 고객센터는 매장 이용, 상품 문의, GS&POINT, 택배 서비스 등에 대한 상담을 제공합니다. 우리동네GS 앱을 통해 상품 주문 및 픽업이 가능합니다.",
    services: ["매장 안내", "상품 문의", "GS&POINT", "택배 서비스", "모바일 쿠폰"],
    logo: "/logos/gs25.svg"
  },
  {
    id: "cu",
    name: "CU 고객센터",
    category: "life",
    subCategory: "편의점",
    phone: "1577-0711",
    website: "https://cu.bgfretail.com",
    operatingHours: "24시간 운영",
    description: "CU 고객센터는 매장 이용, 상품 문의, CU멤버스, 택배 서비스 등에 대한 상담을 제공합니다. 포켓CU 앱을 통해 모바일 쿠폰 및 포인트 사용이 가능합니다.",
    services: ["매장 안내", "상품 문의", "CU멤버스", "택배 서비스", "모바일 쿠폰"],
    logo: "/logos/cu.svg"
  },

  // ==================== 공공기관 ====================
  {
    id: "government-110",
    name: "정부민원안내콜센터",
    category: "government",
    subCategory: "정부민원",
    phone: "110",
    website: "https://www.110.go.kr",
    operatingHours: "24시간 운영",
    description: "정부민원안내콜센터(110)는 정부 및 공공기관 관련 모든 민원을 안내하고 상담하는 통합 콜센터입니다. 여권, 주민등록, 세금, 복지 등 다양한 행정 서비스를 안내받을 수 있습니다.",
    services: ["민원 안내", "정책 안내", "기관 연결", "불편 신고", "민원 접수"],
    logo: "/logos/gov.svg"
  },
  {
    id: "nhis",
    name: "국민건강보험공단 고객센터",
    category: "government",
    subCategory: "건강보험",
    phone: "1577-1000",
    website: "https://www.nhis.or.kr",
    locationUrl: "https://www.nhis.or.kr/nhis/index.do",
    operatingHours: "평일 09:00~18:00",
    description: "국민건강보험공단 고객센터는 건강보험료 납부, 자격 확인, 건강검진 예약, 각종 증명서 발급 등의 서비스를 제공합니다. The건강보험 앱을 통해 보험료 조회 및 납부가 가능합니다.",
    services: ["보험료 조회", "자격 확인", "건강검진 예약", "증명서 발급", "급여 신청"],
    logo: "/logos/nhis.svg"
  },
  {
    id: "nps",
    name: "국민연금공단 고객센터",
    category: "government",
    subCategory: "연금",
    phone: "1355",
    website: "https://www.nps.or.kr",
    locationUrl: "https://www.nps.or.kr/jsppage/info/easy/easy_01.jsp",
    operatingHours: "평일 09:00~18:00",
    description: "국민연금공단 고객센터는 연금 가입, 납부 내역 조회, 연금 수령, 각종 증명서 발급 등의 서비스를 제공합니다. 내연금 앱을 통해 예상 연금액 조회가 가능합니다.",
    services: ["가입 내역 조회", "연금 수령", "증명서 발급", "반환일시금", "유족연금"],
    logo: "/logos/nps.svg"
  },
  {
    id: "nts",
    name: "국세청 고객센터",
    category: "government",
    subCategory: "세금",
    phone: "126",
    website: "https://www.nts.go.kr",
    operatingHours: "평일 09:00~18:00",
    description: "국세청 고객센터는 세금 신고, 납부, 환급, 증명서 발급 등 세금 관련 모든 상담을 제공합니다. 홈택스를 통해 온라인으로 각종 세금 신고 및 납부가 가능합니다.",
    services: ["세금 신고", "납부 안내", "환급 조회", "증명서 발급", "세무 상담"],
    logo: "/logos/nts.svg"
  },
  {
    id: "moel",
    name: "고용노동부 고객센터",
    category: "government",
    subCategory: "고용",
    phone: "1350",
    website: "https://www.moel.go.kr",
    operatingHours: "평일 09:00~18:00",
    description: "고용노동부 고객센터는 실업급여, 근로조건, 산업재해 등 고용 및 노동 관련 모든 상담을 제공합니다. 워크넷을 통해 취업 정보 및 실업급여 신청이 가능합니다.",
    services: ["실업급여", "근로조건 상담", "산업재해", "취업 지원", "노동권익"],
    logo: "/logos/moel.svg"
  },
  {
    id: "kcomwel",
    name: "근로복지공단 고객센터",
    category: "government",
    subCategory: "복지",
    phone: "1588-0075",
    website: "https://www.kcomwel.or.kr",
    operatingHours: "평일 09:00~18:00",
    description: "근로복지공단 고객센터는 산재보험, 고용보험, 퇴직연금 등 근로자 복지 관련 상담을 제공합니다. 토탈서비스를 통해 온라인 업무 처리가 가능합니다.",
    services: ["산재보험", "고용보험", "퇴직연금", "대부 사업", "복지 시설"],
    logo: "/logos/kcomwel.svg"
  },

  // ==================== 의료·건강 ====================
  {
    id: "samsung-medical",
    name: "삼성서울병원 고객센터",
    category: "healthcare",
    subCategory: "대학병원",
    phone: "02-3410-2114",
    website: "https://www.samsunghospital.com",
    locationUrl: "https://www.samsunghospital.com/home/reservation/reservationInfo.do",
    operatingHours: "평일 08:00~17:00 / 토요일 08:00~12:00",
    description: "삼성서울병원 고객센터는 진료 예약, 건강검진 예약, 진료비 수납, 제증명 발급 등의 서비스를 제공합니다. 삼성병원 앱을 통해 간편하게 진료 예약이 가능합니다.",
    services: ["진료 예약", "건강검진 예약", "진료비 수납", "제증명 발급", "입퇴원 안내"],
    logo: "/logos/samsung-hospital.svg"
  },
  {
    id: "asan-medical",
    name: "서울아산병원 고객센터",
    category: "healthcare",
    subCategory: "대학병원",
    phone: "1688-7575",
    altPhone: "02-3010-1300",
    website: "https://www.amc.seoul.kr",
    locationUrl: "https://www.amc.seoul.kr/asan/healthinfo/map/mapList.do",
    operatingHours: "평일 08:00~17:30 / 토요일 08:00~12:30",
    description: "서울아산병원 고객센터는 진료 예약, 검사 예약, 입퇴원 안내, 제증명 발급 등의 서비스를 제공합니다. 암병원 예약은 별도 번호로 연결됩니다.",
    services: ["진료 예약", "검사 예약", "입퇴원 안내", "제증명 발급", "암병원"],
    logo: "/logos/asan.svg"
  },
  {
    id: "snuh",
    name: "서울대병원 고객센터",
    category: "healthcare",
    subCategory: "대학병원",
    phone: "1588-5700",
    website: "https://www.snuh.org",
    locationUrl: "https://www.snuh.org/intro/location.do",
    operatingHours: "평일 08:30~17:30",
    description: "서울대학교병원 고객센터는 진료 예약, 건강검진, 입퇴원 수속 등의 서비스를 제공합니다. 서울대병원 앱을 통해 간편하게 예약할 수 있습니다.",
    services: ["진료 예약", "건강검진", "입퇴원 수속", "제증명 발급", "주차 안내"],
    logo: "/logos/snuh.svg"
  },

  // ==================== 엔터테인먼트 ====================
  {
    id: "netflix",
    name: "넷플릭스 고객센터",
    category: "entertainment",
    subCategory: "OTT",
    phone: "080-001-9587",
    website: "https://www.netflix.com",
    operatingHours: "24시간 운영",
    description: "넷플릭스 고객센터는 계정 관리, 결제 문의, 콘텐츠 재생 문제 등에 대한 상담을 제공합니다. 넷플릭스 앱 내 도움말 센터를 통해 자가 해결도 가능합니다.",
    services: ["계정 관리", "결제 문의", "재생 문제", "프로필 설정", "구독 변경"],
    logo: "/logos/netflix.svg"
  },
  {
    id: "wavve",
    name: "웨이브 고객센터",
    category: "entertainment",
    subCategory: "OTT",
    phone: "1599-3709",
    website: "https://www.wavve.com",
    operatingHours: "평일 09:00~18:00",
    description: "웨이브 고객센터는 국내 OTT 서비스로 계정 관리, 결제, 콘텐츠 문의 등에 대한 상담을 제공합니다. 지상파 및 종편 실시간 시청이 가능합니다.",
    services: ["계정 관리", "결제 문의", "재생 문제", "구독 변경", "콘텐츠 문의"],
    logo: "/logos/wavve.svg"
  },
  {
    id: "nexon",
    name: "넥슨 고객센터",
    category: "entertainment",
    subCategory: "게임",
    phone: "1588-7701",
    website: "https://www.nexon.com",
    operatingHours: "24시간 운영",
    description: "넥슨 고객센터는 메이플스토리, FIFA 온라인, 카트라이더 등 넥슨 게임에 대한 상담을 제공합니다. 계정 문의, 결제 문제, 게임 내 버그 신고 등이 가능합니다.",
    services: ["계정 문의", "결제 문의", "버그 신고", "게임 상담", "보안 서비스"],
    logo: "/logos/nexon.svg"
  },
  {
    id: "ncsoft",
    name: "엔씨소프트 고객센터",
    category: "entertainment",
    subCategory: "게임",
    phone: "1600-0020",
    altPhone: "1566-7004",
    website: "https://www.ncsoft.com",
    operatingHours: "24시간 운영",
    description: "엔씨소프트 고객센터는 리니지, 블레이드앤소울 등 엔씨소프트 게임에 대한 상담을 제공합니다. PC게임과 모바일게임 고객센터가 분리되어 있습니다.",
    services: ["계정 문의", "결제 문의", "버그 신고", "게임 상담", "보안 서비스"],
    logo: "/logos/ncsoft.svg"
  },
  {
    id: "netmarble",
    name: "넷마블 고객센터",
    category: "entertainment",
    subCategory: "게임",
    phone: "1588-3995",
    altPhone: "1588-5180",
    website: "https://www.netmarble.com",
    operatingHours: "24시간 운영",
    description: "넷마블 고객센터는 모바일 게임 및 PC 게임에 대한 상담을 제공합니다. 세븐나이츠, 모두의마블 등 넷마블 게임 관련 문의가 가능합니다.",
    services: ["계정 문의", "결제 문의", "버그 신고", "게임 상담", "이벤트 문의"],
    logo: "/logos/netmarble.svg"
  },

  // ==================== 컴퓨터·IT ====================
  {
    id: "lenovo",
    name: "레노버 고객센터",
    category: "computer",
    subCategory: "노트북·PC",
    phone: "1670-0088",
    website: "https://www.lenovo.com/kr",
    locationUrl: "https://support.lenovo.com/kr/ko/serviceprovider",
    operatingHours: "평일 09:00~18:00 / 토요일 09:00~12:00",
    description: "레노버 고객센터는 씽크패드, 아이디어패드, 요가 등 레노버 노트북 및 PC에 대한 기술 지원 및 수리 서비스를 제공합니다. 온라인 진단 도구를 통한 자가 진단도 가능합니다.",
    services: ["기술 지원", "노트북 수리", "부품 구매", "워런티 확인", "드라이버 다운로드"],
    logo: "/logos/lenovo.svg"
  },
  {
    id: "asus",
    name: "에이수스 고객센터",
    category: "computer",
    subCategory: "노트북·PC",
    phone: "1566-6868",
    website: "https://www.asus.com/kr",
    locationUrl: "https://www.asus.com/kr/support/Service-Center/Korea",
    operatingHours: "평일 09:00~18:00",
    description: "에이수스(ASUS) 고객센터는 ROG 게이밍 노트북, 젠북, 비보북 등 에이수스 제품에 대한 기술 지원 및 수리 서비스를 제공합니다.",
    services: ["기술 지원", "노트북 수리", "부품 구매", "워런티 확인", "드라이버 다운로드"],
    logo: "/logos/asus.svg"
  },
  {
    id: "dell",
    name: "델 고객센터",
    category: "computer",
    subCategory: "노트북·PC",
    phone: "080-200-3800",
    website: "https://www.dell.com/ko-kr",
    locationUrl: "https://www.dell.com/support/home/ko-kr",
    operatingHours: "평일 09:00~18:00",
    description: "델(Dell) 고객센터는 XPS, 인스피론, 에일리언웨어 등 델 노트북 및 PC에 대한 기술 지원 및 수리 서비스를 제공합니다. 프리미엄 지원 서비스도 이용 가능합니다.",
    services: ["기술 지원", "노트북 수리", "부품 구매", "프리미엄 지원", "드라이버 다운로드"],
    logo: "/logos/dell.svg"
  },
]

export function getServiceCentersByCategory(categoryId: string): ServiceCenter[] {
  return serviceCenters.filter(center => center.category === categoryId)
}

export function searchServiceCenters(query: string): ServiceCenter[] {
  const lowercaseQuery = query.toLowerCase()
  return serviceCenters.filter(center => 
    center.name.toLowerCase().includes(lowercaseQuery) ||
    center.description.toLowerCase().includes(lowercaseQuery) ||
    center.services.some(service => service.toLowerCase().includes(lowercaseQuery))
  )
}

export function getPopularCenters(): ServiceCenter[] {
  const popularIds = [
    "samsung-electronics", "lg-electronics", "apple-korea", "skt", "kt", "lguplus",
    "hyundai-motor", "kia-motor", "coupang", "baemin", "korean-air", "kb-bank"
  ]
  return serviceCenters.filter(center => popularIds.includes(center.id))
}
